### ISSUE TITLE
Ruby 2.4 dropped xmlrpc from stdlib

### ISSUE THREAD

**Issue by stuwil** [sensu-plugins/sensu-plugins-supervisor#20]
See the [relevant Ruby change](https://bugs.ruby-lang.org/issues/12160). The [gem was extracted](https://github.com/ruby/xmlrpc), but has a minimum requirement of 2.3. This is affecting master... @majormoses, any ideas on how to handle?

**Comment by majormoses** [comment]
Ya this has plagued us: #19 #15 #18 #17

**Comment by majormoses** [comment]
I think we need to roll back to pre 2.4 support and figure out how to handle this going foward.

**Comment by stuwil** [comment]
#21 should cover anything below 2.4.

**Comment by majormoses** [comment]
yes I will fix to 2.1-2.3 as previously tested by travis.

**Comment by stuwil** [comment]
Alternatively, know of a way to conditionally have a gem installed based on the Ruby version? I could update that branch to install xmlrpc only on 2.4+, which should fix it across the board.

**Comment by majormoses** [comment]
I was just looking at the pr and was about to check out the new dependencies. If that does not look bad I am all for that. If not what I was gonna do was rollback to 2.3 compatible with a check in the code to call the right way based on version knowing it did not solve the gem install and gemspec goodness and would need to solve that later by writing a c extension and do that.

**Comment by majormoses** [comment]
I dont see any issues with that I am gonna go that approach.

**Comment by stuwil** [comment]
Yeah, that PR won't fix anything on 2.4. Unfortunately, even rolling back won't... xmlrpc was never a dependency as it was stdlib up until 2.4.

**Comment by majormoses** [comment]
does ox not support ruby 2.4?

**Comment by majormoses** [comment]
so we can conditionally install the gem based on the version by writing a c extension: http://www.programmersparadox.com/2012/05/21/gemspec-loading-dependent-gems-based-on-the-users-system

**Comment by stuwil** [comment]
Ox works in 2.4.

So in order to support 2.4, the `xmlrpc` gem needs to be conditionally required (it's usage in this check predates the recent PRs on this).

**Comment by majormoses** [comment]
I have not written c in a few years so I am not gonna have a chance to getting around to giving this a shot until the weekend.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-supervisor/versions/1.1.0
